sudo: false
language: python
python:
- 2.7
cache:
  apt: true
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/download"
env:
  global:
  - TEST_DIR=/tmp/test_dir
  - MODULE=protoclass
  - OMP_NUM_THREADS=4
  - OPENBLAS_NUM_THREADS=4
  - USERNAME="glemaitre"
  - EMAIL="g.lemaitre58@gmail.com"
  - secure: N/EdgFgllqYCTOgCNacsOxpTk2A9Z73xcQEnht+6sWtqW3BnUwWA9IggKalapLC7Vrel0F1RPB7sTQABzFiAk7WhW5+6ZgzrAFZEqdcyY8UsEsC2WHFgiU9kj+/vn9RGcyHxHRGqFnMVxcabb/4UH7hz5s4Xx0/XjQt8c7HwX4cJ0LtX64qEUL1jRUG7glzgTWvjIw3txQHADq+jt12pKkoVo8n9Cvnx761tFziqTIpi01inqlgFN77gqgtlLdXPIyqpFki+1ye0t6V3G3D5UqYRXzpGQSqKz63/7rogpKJHSe7kjzvw/u3ojvfWUi9e5RqpOT1dQneVkuyUSF24qndotoGcp0YflDHuOgvv30yXPqanIErEnrtAWPadxxU4YtCi7RnpEEB6avORI86ZdsL8cwUU9u5vFy3wZT32ZYZhsYjha3gO6FrkqD0W6DzOSqHbgeZoyHboztM6at67Hbzwblw8XUK+c6bLZAe3n2ltCWkhP7l5apEeW+7hqCuGve32YYwqjrt2infmwG5RX4fG0c6Qbr2bQPNM7FmTWfkiBzJ07BmN+twNSFpjI+ZReKYPeyVyeb20GW1VSCmmEDasDxayce5AvpjSjy9MZfLpIMC05jL6GzboggOOiMR2m261F7kX6E5//tKccwIvhGGib5IWnuQMZfYkX3/+z+k=
  matrix:
  - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="true" NUMPY_VERSION="1.10.0" SCIPY_VERSION="0.17.0"
before_install:
- git submodule update --init --recursive
install:
- source build_tools/travis/install.sh
script:
- bash build_tools/travis/push_bibtex.sh
